require "noinv"

include "dialogs/screen"
include "dialogs/mfuPanel"
include "dialogs/kateDlg"
include "dialogs/mainTaskDlg"
include "dialogs/weatherDlg"
include "dialogs/copyDlg"
include "dialogs/badPcDlg"
include "dialogs/petrDlg"
include "dialogs/jannaDlg"
include "dialogs/ownerDlg"
include "dialogs/cookerDlg"
